spring:
  application:
    name: api-svc
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 103.152.165.53
      port: 27017
      database: 'resume'
      username: 'resume'
      password: 'abc123resume'
  rabbitmq:
    host: 18.139.222.137
    port: 5672
    username: admin
    password: rabb@t@7911
    queue: cv.queue
    profile:
      exchange: event.exchange
      queue: event.queue
      routingkey: event.routingkey
    email:
      exchange: email.exchange
      queue: email.queue
      routingkey: email.routingkey
    cv:
      exchange: cv.exchange
      queue: cv.queue
      routingkey: cv.routingkey
    image:
      exchange: image.exchange
      queue: image.queue
      routingkey: image.routingkey

server:
  port: ${API_SVC_PORT:30003}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:30000/eureka/}

logging:
  config: config/log4j2.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

application:
  version: ${VERSION:1.0}

calendar:
  timeCheck: 18000000 #30p = 30*60*1000
  nLoop: 3 #canh bao 3 lan

excel:
  serverPath: /usr/share/nginx/file-rs/attachment/
#  serverPath: D:\
  path: /usr/share/nginx/file-rs/attachment/Profiles.xlsx
#  path: D:\

note:
  domain: http://file-rs.edsolabs.com/attachment/
  serverpath: /usr/share/nginx/file-rs/attachment/
#  serverPath: D:\
  fileSize: 15728640 #Byte 15MB

avatar:
  domain: http://file-rs.edsolabs.com/avatar/
  serverpath: /usr/share/nginx/file-rs/avatar/
#  serverPath: D:\
  fileSize: 15728640 #Byte 15MB