spring:
  application:
    name: api-svc
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 103.152.165.53
      port: 27017
      database: 'resume'
      username: 'resume'
      password: 'abc123resume'

server:
  port: ${API_SVC_PORT:30003}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:30000/eureka/}

logging:
  config: config/log4j2.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

application:
  version: ${VERSION:1.0}

calendar:
  timeCheck: 18000000 #30p = 30*60*1000
  nLoop: 3 #canh bao 3 lan

rabbitmq:
  host: '18.139.222.137'
  port: 5672
  username: 'admin'
  password: 'rabb@t@7911'